# -*- mode: ruby -*-
# vi: set ft=ruby :

CHEF_ENV="camp2012"
CHEF_VALID="../../.chef/validation.pem"
CHEF_URL="http://33.33.33.10:4000"


Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise-server-i386"

  config.vm.define :db do |db_config| 
    db_config.vm.host_name = "dbserver-neu.local"
    db_config.vm.customize ["modifyvm", :id, 
      "--name", "Postgresql DB Server"]

    # Forward a port from the guest to the host, which allows for outside
    # computers to access the VM, whereas host only networking does not.
    # config.vm.forward_port 80, 8080
    db_config.vm.forward_port 5432, 15432
    db_config.vm.network :hostonly, "33.33.33.20"

    # Enable provisioning with chef server, specifying the chef server URL,
    # and the path to the validation key (relative to this Vagrantfile).
    #
 
  
    db_config.vm.provision :chef_client do |chef|
      chef.environment = CHEF_ENV
      chef.chef_server_url = CHEF_URL
      chef.validation_key_path = CHEF_VALID

      # chef.log_level = :debug

      chef.add_role "db-server"
    end
  
  end

  config.vm.define :pool do |pool_config| 
    pool_config.vm.host_name = "dbpool-neu.local"
    pool_config.vm.customize ["modifyvm", :id, 
      "--name", "Postgresql PGPool Server"]

    # Forward a port from the guest to the host, which allows for outside
    # computers to access the VM, whereas host only networking does not.
    # config.vm.forward_port 80, 8080
    pool_config.vm.forward_port 5432, 5432

    # Enable provisioning with chef server, specifying the chef server URL,
    # and the path to the validation key (relative to this Vagrantfile).
    #
 
  
    pool_config.vm.provision :chef_client do |chef|
      chef.environment = CHEF_ENV
      chef.chef_server_url = CHEF_URL
      chef.validation_key_path = CHEF_VALID

      # chef.log_level = :debug

      chef.add_role "db-pool"
    end
  
  end


end
